name: Publish Factorio Mod

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:


jobs:
    publish-mod:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Copy changelog into mod folder
              run: cp changelog.txt src/changelog.txt

            - name: Validate Mod
              uses: TheBrutalX/factorio-mod-uploader-action@v2
              with:
                  action: validate
                  mod-folder: src

            - name: Create zip
              uses: TheBrutalX/factorio-mod-uploader-action@v2
              with:
                  action: compress
                  mod-folder: src
                  auto-update-version: 'false'

            - name: Upload ZIP as Artifact
              uses: actions/upload-artifact@v4
              with:
                name: factorio-mod-zip
                path: ${{ env.ZIP_FILE }}

            - name: Upload Mod
              if: startsWith(github.ref, 'refs/tags/v')
              uses: TheBrutalX/factorio-mod-uploader-action@v2
              with:
                  action: upload
                  factorio-api-key: ${{ secrets.FACTORIO_API_KEY }}

            - name: Create GitHub Release
              if: startsWith(github.ref, 'refs/tags/v')
              uses: softprops/action-gh-release@v2
              with:
                  files: ${{ env.ZIP_FILE }}
                  generate_release_notes: false
