name: Release

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.4.1"

      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install dependencies
        run: |
          luarocks install serpent
          luarocks install busted
          luarocks install luacheck
          luarocks install faketorio

      - name: Run tests
        run: |
          luacheck ./src/*.lua
          luacheck ./src/todo/*.lua
          faketorio package -c .github/.faketorio -v

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            target/*.zip